id = "auto-docs"
name = "Auto Docs"
version = "0.1.0"
description = "Automatic documentation generation with AI"
schema_version = 1
authors = ["gageracer"]
[slash_commands.document]
description = "Generate documentation for a file"
requires_argument = true